volumes:
  mysql-data:
    name: ${PROJECT_NAME}-data

networks:
  network-id:
    name: ${PROJECT_NAME}-network
secrets:
  db_password:
    file: ./secrets/db_password.txt
services:
  mysql:
    image:  mysql:latest
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: /run/secrets/db_password
      MYSQL_ROOT_PASSWORD: /run/secrets/db_password

    volumes:
      - mysql-data:/var/lib/mysql
    secrets:
      - db_password
    ports:
      - "3306:3306"
    restart: always
    networks:
      - network-id

  php:
    build:
      context: ./docker/php
      
    ports:
      - "${PHP_PORT}:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
    networks:
      - network-id
